# Generated by Django 5.1.1 on 2024-10-15 07:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('family_members', '0001_initial'),
        ('investments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investment',
            name='family_member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='family_members.familymember'),
        ),
        migrations.DeleteModel(
            name='FamilyMember',
        ),
    ]
