# Generated by Django 5.1.1 on 2024-10-23 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0002_alter_investment_family_member_delete_familymember'),
    ]

    operations = [
        migrations.RenameField(
            model_name='investment',
            old_name='investment_amount',
            new_name='amount',
        ),
        migrations.RemoveField(
            model_name='investment',
            name='family_member',
        ),
        migrations.AddField(
            model_name='investment',
            name='investment_type',
            field=models.CharField(default='Stocks', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='investment',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
