# Generated by Django 5.1.1 on 2024-10-23 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0003_rename_investment_amount_investment_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investment',
            name='investment_type',
            field=models.CharField(choices=[('Stocks', 'Stocks'), ('Bonds', 'Bonds'), ('Real Estate', 'Real Estate'), ('Gold', 'Gold'), ('ETFs', 'ETFs')], max_length=50),
        ),
    ]
