# Generated by Django 5.1.1 on 2024-11-16 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0004_alter_investment_investment_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='investment',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='investment',
            name='total_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
