# Generated by Django 5.1.1 on 2024-10-18 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('family_members', '0002_alter_familymember_email_alter_familymember_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='familymember',
            name='email',
        ),
        migrations.AddField(
            model_name='familymember',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
